services:
  devserver:
    image: paypwn-devserver:${PAYPWN_VERSION}
    restart: always
    build:
      context: .
      dockerfile: ./devserver/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      DOCKER_BUILDKIT: 1
    expose:
      - "8443:8443"
    networks:
      - paypwn
    user: ${DEVSERVER_UID}:${DEVSERVER_GID}
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ./setup/setup-vite:/setup/setup-vite
      - ./paybuddy/proto:/var/paypwn/paybuddy/proto
      - ./paybuddy/vue:/var/paypwn/paybuddy/vue
      - ./shared/proto:/var/paypwn/shared/proto

  paypwn:
    volumes:
      - ./setup/entrypoint:/var/paypwn/entrypoint
      - ./shared/python:/var/paypwn/shared/python
      - ./paybuddy/python:/var/paypwn/paybuddy/python

  postgres:
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init-db.sql:ro

  nginx:
    volumes:
      - ./nginx/etc/sites:/etc/nginx/sites:ro
