#!/bin/ash

set -eu -o pipefail

PIDS=""

# Start paybuddy
cd /var/paypwn/paybuddy
source venv/bin/activate
export PYTHONPATH=python:protopy:../shared/python
python3 ./python/main.py &
PIDS="${PIDS} ${!}"

# Cleanup all processes on exit
cleanup() {
    for pid in ${PIDS}; do
        kill -TERM "$pid" 2>/dev/null || true
    done
}
trap cleanup EXIT INT TERM

# Wait for anything to terminate
wait -n ${PIDS}
