#!/bin/ash

set -eu

PROJECT="$(basename $(realpath .))"
BASEDIR="/var/paypwn/${PROJECT}"
SHAREDDIR="/var/paypwn/shared"

# Lint with mypy
source "${BASEDIR}/venv/bin/activate"
(
    cd python
    export PYTHONPATH="."
    export PYTHONPATH="${PYTHONPATH}:../../shared/python"
    export PYTHONPATH="${PYTHONPATH}:${BASEDIR}/backend"
    mypy --check-untyped-defs .
)

# Lint shared
(
    cd ../shared/python
    export PYTHONPATH="."
    export PYTHONPATH="${PYTHONPATH}:${BASEDIR}/backend"
    mypy --check-untyped-defs .
)
