#!/bin/ash

set -eu

BASEDIR=/var/paypwn/$(basename $(realpath .))

# Lint with mypy
source "${BASEDIR}/venv/bin/activate"
export PYTHONPATH="${BASEDIR}/protopy/mypy"
export PYTHONPATH="${PYTHONPATH}:${BASEDIR}/protopy"
export PYTHONPATH="${PYTHONPATH}:${BASEDIR}/protopy/pbdantic"
export PYTHONPATH="${PYTHONPATH}:../shared/python"
mypy --check-untyped-defs \
    ./python
