#!/bin/ash

set -eu

# Create virtual environment
if [ ! -d venv ]; then
    python3 -m venv venv
    source venv/bin/activate

    # Install depdendencies
    pip3 install --upgrade pip
    pip3 install -r python/requirements.txt
else
    source venv/bin/activate
fi

# Compile protobuf to python
mkdir -p protopy/pbdantic protopy/mypy
python3 -m grpc_tools.protoc \
    -I=./api \
    --python_out=./protopy \
    --protobuf-to-pydantic_out=./protopy/pbdantic \
    --mypy_out=./protopy/mypy \
    $(ls ./api)
