#!/bin/ash

set -eu

PROJECT="$(basename $(realpath .))"

# Create virtual environment
if [ ! -d venv ]; then
    python3 -m venv venv
    source venv/bin/activate

    # Install depdendencies
    pip3 install --upgrade pip
    pip3 install -r python/requirements.txt
    pip3 install -r ../shared/python/requirements.txt
else
    source venv/bin/activate
fi

# Compile protobuf to python
protoc() {
    local PROJECT="${1}"
    local PROTODIR="${2}"
    local OUTDIR="./backend/${PROJECT}_pb"
    mkdir -p "${OUTDIR}"
    python3 -m grpc_tools.protoc \
        -I"${PROTODIR}" \
        --python_out="${OUTDIR}" \
        --protobuf-to-pydantic_out="${OUTDIR}" \
        --mypy_out="${OUTDIR}" \
        $(find "${PROTODIR}" -type f -name '*.proto')
}

protoc paypwn ../shared/proto
protoc "${PROJECT}" ./proto
