#!/bin/ash

set -eux -o pipefail

# Build paybuddy front-end
cd vue

# Install dependencies
npm install

# Compile protobuf to typescript
mkdir -p src/proto
protoc \
    --plugin=protoc-gen-ts_proto=./node_modules/.bin/protoc-gen-ts_proto \
    --ts_proto_out=./src/proto \
    --ts_proto_opt=outputJsonMethods=true,outputClientImpl=true,esModuleInterop=true \
    --proto_path=../proto \
    $(find ../proto -type f -name '*.proto')

# Build vue
npm run build
