#!/bin/ash

set -eux -o pipefail

# Building for dev?
DEV=0
if [ ${#} -gt 0 ] && [ ${1} == "dev" ]; then
    DEV=1
    shift
fi

# Build paybuddy front-end
cd vue

# Install dependencies
if [ ${DEV} -eq 1 ]; then
    npm install
else
    npm install --production
fi

# Compile protobuf to typescript
mkdir -p src/proto
protoc \
    --plugin=protoc-gen-ts_proto=./node_modules/.bin/protoc-gen-ts_proto \
    --ts_proto_out=./src/proto \
    --ts_proto_opt=outputJsonMethods=true,outputClientImpl=true,esModuleInterop=true \
    --proto_path=../proto \
    $(find ../proto -type f -name '*.proto')
protoc \
    --plugin=protoc-gen-ts_proto=./node_modules/.bin/protoc-gen-ts_proto \
    --ts_proto_out=./src/proto \
    --ts_proto_opt=outputJsonMethods=true,outputClientImpl=true,esModuleInterop=true \
    --proto_path=../../shared/proto \
    $(find ../../shared/proto -type f -name '*.proto')

# Build vue
npm run build
