name: Docker Compose Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: docker compose build

      - name: Run dev front-end linter
        run: ./devserver/lint.sh

      - name: Run dev python linter
        run: ./devserver/mypy.sh --no-cache
