name: Docker Compose Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install yq
        uses: mikefarah/yq@v4

      - name: Build Docker images
        run: docker compose build

      - name: Build mypy image
        run: |
          source .env
          docker build -f ./devserver/Dockerfile.mypy -t "paypwn-mypy:${PAYPWN_VERSION}" .

      - name: Save Docker images as artifact
        run: |
          source .env
          IMAGES=($(docker compose config | yq .services[].image))
          IMAGES+=("paypwn-mypy:${PAYPWN_VERSION}")
          docker save -o images.tar "${IMAGES[@]}"

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v2
        with:
          name: paypwn-images
          path: images.tar

  lint-front-end:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: paypwn-images

      - name: Load Docker images
        run: docker load -i images.tar

      - name: Run front-end linter
        run: ./devserver/lint.sh

  lint-python:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: paypwn-images

      - name: Load Docker images
        run: docker load -i images.tar

      - name: Run python linter
        run: ./devserver/mypy.sh

  run-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v2
        with:
          name: paypwn-images

      - name: Load Docker images
        run: docker load -i images.tar

      - name: Run automated tests
        run: ./devserver/tests.sh
